### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by stianjensen** [aleksanb/TDT4195-Project#2]

**Comment by iver56** [comment]
Yeah, I don't know much about licence.. How about MIT, Apache or Do What the Fuck You Want to Public License?

**Comment by stianjensen** [comment]
It depends if WTFPL is NTNU compatible

**Comment by iver56** [comment]
I guess we can ask Christian & Co on friday

**Comment by stianjensen** [comment]
Interesting choice of license. Why CC?
https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

**Comment by iver56** [comment]
One of the libs we use has a CC licence
https://github.com/aleksanb/TDT4195-Project/blob/master/lib/ntc.js
I don't know if that is a good reason for why this project should have a CC licence.
Is MIT a valid choice? A better choice?

**Comment by stianjensen** [comment]
It's not a share-alike license, so MIT would be a fair choice. I can't see any good reason for the ntc library to have chosen CC.

**Comment by iver56** [comment]
Very well. I changed it to MIT licence.

https://github.com/aleksanb/TDT4195-Project/commit/3fd6566ca6d9b0e925aa1723aca8dc53723ff0c0

**Comment by stianjensen** [comment]
Yay!

**Comment by stianjensen** [comment]
Rebasing the master branch.
![](http://i3.kym-cdn.com/photos/images/original/000/000/681/what-you-did-there-i-see-it.thumbnail.jpg)

**Comment by iver56** [comment]
LOL! xD

**Comment by aleksanb** [comment]
Necro-issue!

**Comment by iver56** [comment]
Being an ISTJ, I have the personality trait "will not rest until a concept is fully learned or a job is well completed" ;)
